# Generated by Django 3.1.1 on 2022-04-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='VehiclesBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.brands'),
        ),
    ]
