# Generated by Django 3.1.1 on 2022-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0002_auto_20220415_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='FromDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ToDate',
            field=models.DateTimeField(null=True),
        ),
    ]
