# Generated by Django 3.1.1 on 2022-04-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0005_auto_20220416_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
